"""empty message

Revision ID: 30391e530e71
Revises: 
Create Date: 2024-02-26 00:54:17.907486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30391e530e71"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "park",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("enter_date", sa.DateTime(), nullable=False),
        sa.Column("checkout_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("park")
    # ### end Alembic commands ###
